name: Build AOSP Android 6.0.0_r1 ARM (Demo on GitHub hosted)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 720

    steps:
      - name: Install dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y openjdk-8-jdk git repo bc bison build-essential \
            curl flex g++-multilib gcc-multilib git-core gnupg gperf lib32ncurses-dev \
            lib32readline-dev lib32z1-dev liblz4-tool libncurses-dev \
            libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop openjdk-8-jdk pngcrush \
            schedtool squashfs-tools xsltproc zip zlib1g-dev liblzma-dev

      - name: Setup repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo 'export PATH=~/bin:$PATH' >> $GITHUB_ENV

      - name: Initialize repo
        run: |
          mkdir aosp
          cd aosp
          repo init -u https://android.googlesource.com/platform/manifest -b android-6.0.0_r1 --depth=1

      - name: Sync repo (shallow)
        run: |
          cd aosp
          repo sync -j2 --no-clone-bundle --no-tags --depth=1

      - name: Setup build environment
        run: |
          cd aosp
          source build/envsetup.sh
          lunch aosp_arm-userdebug

      - name: Attempt build (limited threads)
        run: |
          cd aosp
          make -j2 sdk || true

      - name: Upload partial build artifacts (if any)
        uses: actions/upload-artifact@v4
        with:
          name: aosp-6.0.0_r1-arm-sdk-partial
          path: aosp/out/target/product/generic_arm/sdk/*.img
