name: Build AOSP ISO

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-aosp-iso:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y git-core gnupg flex bison gperf build-essential \
              zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
              libncurses5-dev libncurses5-dev:i386 libstdc++6:i386 \
              x11proto-core-dev libx11-dev lib32z1-dev \
              ccache libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig \
              python-is-python3 xorriso grub-pc-bin mtools

      - name: Prepare temp build dir
        run: |
          mkdir -p /mnt/workspace
          echo "workspace=/mnt/workspace" >> $GITHUB_ENV

      - name: Download repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Init AOSP source
        working-directory: /mnt/workspace
        run: |
          repo init -u https://android.googlesource.com/platform/manifest -b android-13.0.0_r3

      - name: Sync source (takes time)
        working-directory: /mnt/workspace
        run: |
          repo sync -c -j$(nproc) --no-tags --no-clone-bundle

      - name: Build AOSP x86_64
        working-directory: /mnt/workspace
        run: |
          source build/envsetup.sh
          lunch aosp_x86_64-eng
          make -j$(nproc)

      - name: Create bootable ISO
        working-directory: /mnt/workspace
        run: |
          mkdir -p iso/boot/grub
          cp out/target/product/generic_x86_64/kernel iso/bo
