name: Build AOSP Android 10

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup tmp workspace
        run: |
          mkdir -p /tmp/aosp
          echo "TMP_DIR=/tmp/aosp" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y openjdk-8-jdk git curl python3 unzip bc bison build-essential \
            g++-multilib gcc-multilib libncurses5-dev libncurses5-dev:i386 \
            libssl-dev libxml2-utils lzop pngcrush rsync schedtool squashfs-tools \
            xsltproc zip zlib1g-dev liblz4-tool libzstd-dev

      - name: Setup Java
        run: |
          echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac))))" >> $GITHUB_ENV
          echo "$JAVA_HOME/bin" >> $GITHUB_PATH

      - name: Install repo tool
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
          chmod a+x ~/repo
          sudo mv ~/repo /usr/local/bin/repo

      - name: Initialize AOSP 10 source
        working-directory: /tmp/aosp
        run: |
          repo init -u https://android.googlesource.com/platform/manifest -b android-10.0.0_r47

      - name: Sync source (shallow)
        working-directory: /tmp/aosp
        run: |
          repo sync -c --no-tags --no-clone-bundle -j$(nproc)

      - name: Source build and lunch
        working-directory: /tmp/aosp
        run: |
          source build/envsetup.sh
          lunch aosp_arm-userdebug

      - name: Build Android
        working-directory: /tmp/aosp
        run: |
          make -j$(nproc)

      - name: Upload out folder
        uses: actions/upload-artifact@v4
        with:
          name: aosp-android10
          path: /tmp/aosp/out/target/product/generic/

