name: Android-x86 6.0 R1 x86_64 Build (GitHub-hosted demo)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 720

    steps:
      - name: Install dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y openjdk-8-jdk git repo bc bison build-essential \
            curl flex g++-multilib gcc-multilib git-core gnupg gperf lib32ncurses-dev \
            lib32readline-dev lib32z1-dev liblz4-tool libncurses-dev \
            libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop openjdk-8-jdk pngcrush \
            schedtool squashfs-tools xsltproc zip zlib1g-dev liblzma-dev

      - name: Setup repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo 'export PATH=~/bin:$PATH' >> $GITHUB_ENV

      - name: Initialize repo
        run: |
          mkdir android-x86
          cd android-x86
          repo init -u https://github.com/android-x86/manifest.git -b android-6.0-r1 --depth=1

      - name: Sync repo (shallow, fewer threads)
        run: |
          cd android-x86
          repo sync -j2 --no-clone-bundle --no-tags --depth=1

      - name: Setup build environment
        run: |
          cd android-x86
          source build/envsetup.sh
          lunch android_x86_64-userdebug

      - name: Attempt build (limited threads)
        run: |
          cd android-x86
          make -j2 iso_img || true

      - name: Upload partial build artifacts (if any)
        uses: actions/upload-artifact@v4
        with:
          name: android-x86-6.0-r1-x86_64-partial
          path: android-x86/out/target/product/x86_64/*.iso
