name: Build Android 10 ARM (no Docker)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install required packages and Python 2
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk git-core gnupg flex bison gperf \
            build-essential zip curl zlib1g-dev gcc-multilib g++-multilib \
            libc6-dev-i386 libncurses-dev x11proto-dev libx11-dev \
            lib32z-dev ccache libgl1-mesa-dev libxml2-utils xsltproc unzip \
            python-is-python3 python2-minimal || true

          # Manually install Python 2 if not available
          if ! command -v python2 >/dev/null; then
            curl -LO https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz
            tar xzf Python-2.7.18.tgz
            cd Python-2.7.18
            ./configure --prefix=/usr/local
            make -j$(nproc)
            sudo make install
            cd ..
          fi

      - name: Set up environment
        run: |
          echo 'JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64' >> $GITHUB_ENV
          echo "$JAVA_HOME/bin" >> $GITHUB_PATH

      - name: Initialize AOSP repo
        run: |
          mkdir aosp && cd aosp
          curl https://storage.googleapis.com/git-repo-downloads/repo > repo
          chmod +x repo
          sudo mv repo /usr/local/bin/
          repo init -u https://android.googlesource.com/platform/manifest -b android-10.0.0_r47

      - name: Sync AOSP source (may take 30+ minutes)
        run: |
          cd aosp
          repo sync -c -j4

      - name: Build AOSP for ARM
        run: |
          cd aosp
          source build/envsetup.sh
          lunch aosp_arm-eng
          make -j$(nproc)

      - name: Upload images
        uses: actions/upload-artifact@v4
        with:
          name: android10-arm-output
          path: aosp/out/target/product/generic/*.img
