name: Build AOSP 6.0 on ubuntu-latest

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install legacy dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common curl wget unzip git gnupg flex bison gperf \
            build-essential zip zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses-dev \
            lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc fontconfig
      
          # Install Python 2
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          sudo apt-get update
          sudo apt-get install -y python2
      
          # Install OpenJDK 7 manually
          wget https://github.com/AdoptOpenJDK/openjdk7-binaries/releases/download/jdk7u181-b01/OpenJDK7U-jdk_x64_linux_7u181b01.tar.gz
          mkdir -p ~/java7
          tar -xzf OpenJDK7U-jdk_x64_linux_7u181b01.tar.gz -C ~/java7 --strip-components=1
          echo "JAVA_HOME=$HOME/java7" >> $GITHUB_ENV
          echo "$HOME/java7/bin" >> $GITHUB_PATH

      - name: Install repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Init AOSP 6.0 repo
        run: |
          mkdir aosp && cd aosp
          repo init -u https://android.googlesource.com/platform/manifest -b android-6.0.1_r81
          repo sync -j4

      - name: Build AOSP
        run: |
          cd aosp
          source build/envsetup.sh
          lunch aosp_arm-eng
          make -j$(nproc)

      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: android6-images
          path: aosp/out/target/product/generic/*.img
