name: Build Android Oreo Go x86_64 ISO

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android-oreo-go:
    runs-on: ubuntu-latest
    timeout-minutes: 180  # 3 hours, adjust if needed

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup 100GB tmpfs on /tmp
        run: |
          sudo mount -t tmpfs -o size=100G tmpfs /tmp
          df -h /tmp

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-8-jdk git repo bc bison flex libssl-dev curl \
                                  libncurses5-dev lib32z1-dev libbz2-dev gcc-multilib g++-multilib

      - name: Initialize repo for Android Oreo Go (x86_64)
        run: |
          cd /tmp
          repo init -u https://github.com/android-x86/manifest.git -b android-8.1.0_r49
          repo sync -c -j$(nproc) --no-tags --no-clone-bundle

      - name: Setup environment and lunch for x86_64 Oreo Go
        run: |
          cd /tmp
          source build/envsetup.sh
          lunch android_x86_64-userdebug

      - name: Build Android Oreo Go ISO
        run: |
          cd /tmp
          make iso_img -j$(nproc)

      - name: Copy ISO to workspace
        run: |
          cp /tmp/out/target/product/x86_64/android_x86_64.iso $GITHUB_WORKSPACE/android_oreo_go_x86_64.iso

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-oreo-go-x86_64-iso
          path: android_oreo_go_x86_64.iso

      - name: Unmount tmpfs from /tmp
        if: always()
        run: |
          sudo umount /tmp
