name: Build AOSP 10 in /tmp

on:
  workflow_dispatch:

jobs:
  build-aosp:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-8-jdk git curl python3 unzip bc bison build-essential \
            g++-multilib gcc-multilib libncurses5-dev libncurses5-dev:i386 \
            libssl-dev libxml2-utils lzop pngcrush rsync schedtool squashfs-tools \
            xsltproc zip zlib1g-dev liblz4-tool libzstd-dev

      - name: Prepare /tmp build root
        run: |
          mkdir -p /tmp/aosp
          echo "Using /tmp for AOSP source and build"
          df -h /tmp

      - name: Download and sync AOSP 10 into /tmp
        run: |
          cd /tmp/aosp
          curl https://storage.googleapis.com/git-repo-downloads/repo > repo
          chmod +x repo
          ./repo init -u https://android.googlesource.com/platform/manifest -b android-10.0.0_r1
          ./repo sync -c -j2

      - name: Set up environment
        run: |
          cd /tmp/aosp
          export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
          source build/envsetup.sh
          lunch aosp_arm-eng

      - name: Build system image
        run: |
          cd /tmp/aosp
          export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
          make -j$(nproc) systemimage

      - name: Export built images
        run: |
          mkdir -p $GITHUB_WORKSPACE/out
          cp /tmp/aosp/out/target/product/*/system.img $GITHUB_WORKSPACE/out/ || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: system-img
          path: out/system.img
