name: Build Android-x86 Marshmallow 6.0.0_r1 x86_64 ISO

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android-x86-marshmallow:
    runs-on: ubuntu-latest
    timeout-minutes: 300

    steps:
      - name: Setup 100GB tmpfs on /tmp
        run: |
          sudo mount -t tmpfs -o size=100G tmpfs /tmp
          df -h /tmp

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-8-jdk git repo bc bison flex libssl-dev curl \
                                  libncurses5-dev lib32z1-dev libbz2-dev gcc-multilib g++-multilib

      - name: Initialize repo for Android-x86 Marshmallow 6.0.0_r1 and patch URLs
        run: |
          cd /tmp
          repo init -u https://github.com/android-x86/manifest.git -b android-6.0.0_r1
          # Patch platform URLs to android-x86 forks to avoid 404 errors
          sed -i 's|https://github.com/platform/|https://github.com/android-x86/platform-|g' .repo/manifests/default.xml
          repo sync -c -j$(nproc) --no-tags --no-clone-bundle

      - name: Setup build environment and lunch target
        run: |
          cd /tmp
          source build/envsetup.sh
          lunch android_x86_64-userdebug

      - name: Build Android-x86 Marshmallow ISO
        run: |
          cd /tmp
          make iso_img -j$(nproc)

      - name: Copy ISO to workspace
        run: |
          cp /tmp/out/target/product/x86_64/android_x86_64.iso $GITHUB_WORKSPACE/android_x86_marshmallow_6_0_0_r1_x86_64.iso

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-x86-marshmallow-6.0.0_r1-x86_64-iso
          path: android_x86_marshmallow_6_0_0_r1_x86_64.iso

      - name: Unmount tmpfs from /tmp
        if: always()
        run: |
          sudo umount /tmp
