name: Build AOSP Android 6.0.0_r1 ARM (Legacy Fixes)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 720

    steps:
      - name: Install dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y openjdk-7-jdk python2 git curl bc bison build-essential \
            flex g++-multilib gcc-multilib git-core gnupg gperf lib32ncurses-dev \
            lib32readline-dev lib32z1-dev liblz4-tool libncurses-dev \
            libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush \
            schedtool squashfs-tools xsltproc zip zlib1g-dev liblzma-dev

          sudo ln -sf /usr/bin/python2 /usr/bin/python

      - name: Set JAVA_HOME for Java 7
        run: echo "JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64" >> $GITHUB_ENV

      - name: Setup repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo 'export PATH=~/bin:$PATH' >> $GITHUB_ENV

      - name: Initialize AOSP repo
        run: |
          mkdir aosp
          cd aosp
          repo init -u https://android.googlesource.com/platform/manifest -b android-6.0.0_r1 --depth=1

      - name: Sync AOSP source
        run: |
          cd aosp
          repo sync -j2 --no-clone-bundle --no-tags

      - name: Set up build environment
        run: |
          cd aosp
          export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
          source build/envsetup.sh
          lunch aosp_arm-userdebug

      - name: Start build (limited threads)
        run: |
          cd aosp
          export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
          make -j2 sdk || true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aosp-6.0.0_r1-sdk
          path: aosp/out/target/product/generic/sdk/
